# Generated by Django 4.2.8 on 2024-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
                ("vote_average", models.FloatField(null=True)),
                ("vote_count", models.IntegerField(null=True)),
                ("popularity", models.FloatField(null=True)),
                ("poster_path", models.CharField(max_length=200, null=True)),
                ("backdrop_path", models.CharField(max_length=200, null=True)),
                ("original_language", models.CharField(max_length=10, null=True)),
                ("genre_ids", models.JSONField(null=True)),
                ("raw_data", models.JSONField(null=True)),
            ],
        ),
    ]
