# Generated by Django 4.2.8 on 2024-05-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="genre_ids", new_name="genres",
        ),
    ]
