# Generated by Django 4.2.8 on 2024-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="still_cut_paths",
            field=models.JSONField(null=True),
        ),
    ]
