# Generated by Django 4.2.8 on 2024-05-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_still_cut_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_set",
                to="movies.movie",
            ),
        ),
    ]
