# Generated by Django 4.2.8 on 2024-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_genres_movie_genre_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="genres", field=models.JSONField(null=True),
        ),
    ]
