# Generated by Django 4.2.8 on 2024-05-20 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_alter_review_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review_likes_users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="liked_movies",
            field=models.ManyToManyField(
                blank=True, related_name="liked_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Movie_likes_users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_movie",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
