# Generated by Django 4.2.8 on 2024-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
