# Generated by Django 4.2.8 on 2024-05-20 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0005_review_likes_users_movie_liked_movies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review_likes_users",
            name="review",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="movies.review",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review_likes_users",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_review",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie_likes_users",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="movies.movie",
            ),
        ),
    ]
