# Generated by Django 4.2.8 on 2024-05-23 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0006_comment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="likestatus",
            field=models.ManyToManyField(
                blank=True, related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
