# Generated by Django 4.2.8 on 2024-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_review_likestatus"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="likestatus",),
    ]
