# Generated by Django 4.2.8 on 2024-05-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movie_adult"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="adult",),
    ]
