# Generated by Django 4.2.8 on 2024-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_review_likestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="similarity_score",
            field=models.FloatField(default=0.0),
        ),
    ]
