# Generated by Django 4.2.8 on 2024-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_remove_movie_adult"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="backdrop_path",),
        migrations.RemoveField(model_name="movie", name="original_language",),
        migrations.RemoveField(model_name="movie", name="popularity",),
        migrations.RemoveField(model_name="movie", name="raw_data",),
        migrations.RemoveField(model_name="movie", name="vote_average",),
        migrations.RemoveField(model_name="movie", name="vote_count",),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="title", field=models.CharField(max_length=255),
        ),
    ]
