# Generated by Django 4.2.8 on 2024-05-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_remove_movie_backdrop_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="production_countries",
            field=models.JSONField(null=True),
        ),
    ]
