# Generated by Django 4.2.8 on 2024-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_movie_similarity_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
