# Generated by Django 4.2.8 on 2024-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_movie_production_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="runtime", field=models.IntegerField(null=True),
        ),
    ]
